language: node_js
node_js: 14

addons:
  apt:
    packages:
      - libgconf-2-4 # Required by cypress

cache:
  yarn: true
  directories:
    - '~/.cache' # Required by cypress

script:
  - yarn build
  - yarn test

deploy:
  - provider: npm
    email: tylergrinn@gmail.com
    api_key:
      secure: fmQOvlqbogMaSvfgEUUWMw1AwzVN4fUHwNbU7qYf0LYiUsBMabSInyOJCIS3oQQTMQzdjEW6K/CYe0QOj187aBnnZc2eUOnd07LPMaCwlb2wRX0Us3cxLqSzBnhM2C0Pzcp1LKL7x8gyf+a83WkWRC9vfkZZ61YCDSmpQvu1GHeFdoY1qWs16yzVLnCZ1KLY5Fj6AAvTe2U+oKne8NDjdWRpJSIwr2nxLNBhU76ytehtGg3Z3k4QV9OjBqkWSIIan6Ps0A9GtbgEQeUoBJq1JQhuUdJXBBtySvMz88dGgk7l/fNOKrG1XTsIo+d0YDdTDbdNPslWL6KfGYDHM+b308J6fIU/FhExcw11UxBtzEv4Mrr05vmJxnmXHXY471+64p6DcR/U7YutsIIctDmgJ3oUhVmMITMNQ5KJg7QYdLyWlmur5lfN+smd4cbJmwAWP7Bdd9RL2emV1eimA4qUfTQe71wHVsuQzeFBSEfOeMejHXp5C2SUlXiHN3zM29546Iq7BWMxvO/dzqMRdakUjoWEFCalZs2tyZyFxdPkDNT9i9+4MjPme1lABv2zVKpJ71dcqu2qVoxpIWLVpDF25ntZSvxHcPDdXUgzB0g2lH5fW9/Jvdn2q//TX+Dafnop8Z7//Pi6L/5Z9wFxPcSvLwHNEu86NGTCqeJYDErISgA=
    on:
      tags: true
      repo: tylergrinn/vue-pie-chart
    skip_cleanup: true

  - provider: surge
    project: dist
    domain: vue-pie-chart.surge.sh
    on:
      tags: true
      repo: tylergrinn/vue-piec-chart
    skip_cleanup: true
